---
run:
  modules-download-mode: readonly
linters:
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # disabled
    - depguard
    - dogsled
    - exhaustruct
    - forbidigo
    - gomnd
    - ireturn
    - nonamedreturns
    - prealloc
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  testifylint:
    enable-all: true
    disable:
      - require-error
  paralleltest:
    ignore-missing: true
issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - revive
      text: "dot-imports"
    - path: _test\.go$
      linters:
        - containedctx
